### ISSUE TITLE
Change Redis dependency values from AWS to DO

### ISSUE THREAD

**Issue by Oigen43** [paralect/ship-deploy#10]
All depencides configured for Digital Ocean except Redis

```
redis:
  nodeSelector:
    eks.amazonaws.com/nodegroup: pool-app

password: super-secured-password
```
